name: Delete-Old-Releases

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 * * *' 

jobs:
  delete_old_releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gh CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: List recent releases
      run: gh release list --limit 3 --json name

    - name: Delete old releases
      run: |
        releases=$(gh release list --limit 3 --json name | jq -r '.[].name')
        for release in $releases; do
          gh release delete $release
        done
